openapi: 3.0.3
info:
  title: another-example-spec
  description: The API that powers Optic
  version: 0.1.0
paths:
  /filler_route:
    post:
      summary: Create a new thinga
      description: Create a new thinga
      operationId: cresdfateThingaaaa
      tags:
        - Thing
      responses:
        "201":
          description: Creatsed thing succeszsfullya
          content:
            application/json:
              schema:
                type: object
                description: thiang resource object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: d5b640e5-d88ca-4c17-9bf0-93597b7a1ce2a
