openapi: 3.0.3
info:
  title: example-spec
  description: The API that powers Optic
  version: 0.1.0
paths:
  /filler_route:
    post:
      summary: Create a newa thwinga
      description: Create a new thinga
      operationId: createThing
      tags:
        - Thing
      responses:
        "201":
          description: Created thiaaasdng successfullya
          content:
            application/json:
              schema:
                type: object
                description: thing resource object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: d5b60e5-d88c-4c17-9bf0-93597b7a1ce2
